runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
    # - git clone https://github.com/paulcjh/transformers.git
    - git clone -b ph/pc-1044-streaming-runs https://github.com/mystic-ai/pipeline.git
  python:
    version: "3.10"
    requirements:
      # - "-e ./transformers"
      - "transformers"
      - "-e ./pipeline"
      - "torch==2.0.1"
      - "diffusers"
      - "accelerate"
      - "torchvision"
accelerators: ["nvidia_a100"]
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: sdxl-lightning-streaming
readme: README.md
