runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
  python:
    version: "3.11"
    requirements:
      - "transformers==4.38.2"
      - "git+https://github.com/mystic-ai/pipeline.git@ph/pc-1044-streaming-runs"
      - "torch==2.2.1"
      - "diffusers==0.27.0"
      - "accelerate==0.28.0"
accelerators: ["nvidia_a100"]
pipeline_graph: new_pipeline:my_pipeline
pipeline_name: mistral-7b-streaming
