runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
    # - git clone https://github.com/paulcjh/transformers.git
  python:
    version: "3.10"
    requirements:
      - "-e ./transformers"
      - "pipeline-ai"
      - "torch==2.0.1"
      - "diffusers"
      - "accelerate"
accelerators: ["nvidia_a100"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_pipeline
pipeline_name: paulh/mistral-7b-streaming
