runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
    - apt-get install -y gcc && echo ""
  python:
    version: "3.10"
    requirements:
      - git+https://github.com/mystic-ai/pipeline.git@v2.0.0
      - "torch==2.0.1"
      - "transformers"
      - "diffusers==0.19.3"
      - "accelerate==0.21.0"
      - "vllm==0.2.1.post1"
    cuda_version: "11.4"
accelerators: ["nvidia_a100"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_pipeline
pipeline_name: paulcjh/mistral-7b
