runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
  python:
    version: "3.10"
    requirements:
      - pipeline-ai
      - transformers==4.37.2
      - torch==2.2.0
      - accelerate==0.26.1
      - diffusers==0.26.2
    cuda_version: "11.4"
accelerators: ["nvidia_l4"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: paulh/dreamshaper-xl-turbo
description: null
readme: null
extras: {}
cluster: null
