runtime:
  container_commands:
  - apt update -y
  python:
    version: '3.10'
    requirements:
    - pipeline-ai
accelerators: [nvidia_a100_20gb]
accelerator_memory: 15000
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: sketch-2-img
description: null
readme: README.md
extras: {}
cluster: null