runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
  python:
    version: "3.10"
    requirements:
      - pipeline-ai
      - torch==2.0.1
      - requests==2.30.0
      - transformers==4.32.0
      - pillow==10.0.0
    cuda_version: "11.4"
accelerators: ["nvidia_a100"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: blip-2
description: null
readme: null
extras: {}
