runtime:
  container_commands:
  - apt-get update
  - apt-get install -y git
  python:
    python_version: '3.10'
    python_requirements:
    - git+https://github.com/mystic-ai/pipeline.git@ph/just-balls-in-holes
    cuda_version: '11.4'
accelerators: []
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: mysticai/matthew_test
