runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
  python:
    version: "3.10"
    requirements:
      - pipeline-ai
      - diffusers==0.24.0
      - torch==2.1.1
      - transformers==4.35.2
      - accelerate==0.25.0
accelerators: ["nvidia_a100"]
readme: README.md
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: stable-diffusion-v1.5
extras: {}
