runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
  python:
    version: "3.10"
    requirements:
      - git+https://github.com/mystic-ai/pipeline.git@v2.0.0
      - torch==2.0.1
      - audiocraft
    cuda_version: "11.4"
accelerators: ["nvidia_a100"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: plutopulp/musicgen-large
description: null
readme: null
extras: {}
