runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git libgl1-mesa-glx ffmpeg gcc
  python:
    version: "3.10"
    requirements:
      - pipeline-ai
      - torch==2.0.1
      - audiocraft
accelerators: ["nvidia_a100"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: musicgen-large
description: null
readme: null
extras: {}
