runtime:
  container_commands:
    - apt-get update
    - apt-get install -y ffmpeg git
  python:
    version: "3.10"
    requirements:
      - pipeline-ai
      - transformers==4.37.2
      - torch==2.2.0
      - accelerate==0.27.2
      - pytube==15.0.0
      - moviepy==1.0.3
accelerators: ["nvidia_l4"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: paulh/youtube-transcript
description: null
readme: README.md
extras: {}
cluster: null
