runtime:
  container_commands:
    - apt-get update
    - apt-get install -y git
  python:
    version: "3.10"
    requirements:
      - pipeline-ai
      - torch==2.0.1
      - transformers==4.30.2
      - accelerate==0.21.0
    cuda_version: "11.4"
accelerators: ["nvidia_l4"]
accelerator_memory: null
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: plutopulp/whisper-large
description: null
readme: null
extras: {}
